export let colorsDefault = {
  '--color-white': '#ffffff',
  '--color-black': '#000000',
  '--color-cultured': '#f9f9f9',
  '--color-turquoise': '#67d7c7',
  '--color-yellow_orange': '#ffa944',
  '--color-tangerine': '#f58300',
  '--color-carolina_blue': '#23a0e9',
  '--color-green': '#00b16a',
  '--color-green_turquoise': '#00b16a',
  '--color-fire_opal': '#f35843',
  '--color-base_eerieblack': '#141414',
  '--color-base_sonicsilver': '#7a7a7a',
  '--color-base_silver': '#c2c2c2',
  '--color-base_lightgray': '#d6d6d6',
  '--color-base_platinum': '#ebebeb',
  '--color-base_cultured': '#f5f5f5',
  '--color-base_white': '#ffffff',
};
